version: '3.9'
services:
  valheim-server:
     image: kaekh/valheim
     restart: "on-failure:5"
     ports:
        - "2456:2456"
        - "2457:2457"
        - "2458:2458"
     volumes:
        - ./data:/opt/valheim/.config/unity3d/IronGate/Valheim
     environment:
        SERVERNAME: 'ServerName'
        WORLDNAME: 'worldName'
        PASSWORD: 'mypassword'
